env: "replenishment"

env_args:
  key: "replenishment_efficient_env-v0"
  map_name: "sku200.3.lowest"
  n_agents: 200
  task_type: "sku200.3_stores.lowest_capacity"
  mode: train
  time_limit: 100
  reward: "reward2_enhanced"
  cross_sku_edges: True
  
